// ===== Emoji → Tags =====

import {
  ALIVE,
  BIG,
  FOOD,
  DANGER,
  ROUND,
  HARD,
  LIQUID,
  SHARP,
  HUMAN,
  PLANT,
  TOOL,
  WEAPON,
  METAL,
  BEAUTY,
  CLOTH,
  LONG,
  HEAVY,
  LIGHT,
  FLIGHT,
  VALUE,
  WARM,
  SHIELD,
  KNOW,
  FAST,
  POWER,
  NOT,
} from './alien-symbols.js';

export const EMOJI_TAGS = new Map([
  // Животные
  ['🐶', [ALIVE, WARM, FAST, SHIELD, HUMAN, VALUE, BEAUTY, NOT(WEAPON)]],
  ['🐱', [ALIVE, BEAUTY, WARM, FAST, LIGHT, NOT(SHIELD)]],
  ['🐭', [ALIVE, FAST, FOOD, LIGHT, WARM, HUMAN, NOT(BIG), NOT(DANGER)]],
  ['🐰', [ALIVE, WARM, FAST, FOOD, BEAUTY, ROUND, LIGHT, NOT(DANGER)]],
  ['🦊', [ALIVE, BEAUTY, FAST, DANGER, WARM, VALUE, NOT(HEAVY)]],
  ['🐻', [ALIVE, BIG, POWER, DANGER, HEAVY, WARM, ROUND, VALUE, NOT(FAST)]],
  [
    '🐸',
    [ALIVE, LIQUID, FAST, DANGER, FOOD, BEAUTY, LIGHT, NOT(BIG), NOT(WARM)],
  ],
  ['🐵', [ALIVE, FAST, POWER, HUMAN, WARM, BEAUTY, NOT(HEAVY)]],
  ['🐔', [ALIVE, FOOD, FLIGHT, WARM, LIGHT, HUMAN, NOT(FAST)]],
  ['🐧', [ALIVE, WARM, SHIELD, BEAUTY, ROUND, VALUE, NOT(FLIGHT)]],
  ['🐢', [ALIVE, HARD, SHIELD, HEAVY, ROUND, VALUE, BEAUTY, NOT(FAST)]],
  ['🦋', [ALIVE, BEAUTY, FLIGHT, LIGHT, PLANT, ROUND, NOT(HEAVY)]],

  // Еда
  ['🍎', [FOOD, ROUND, PLANT, BEAUTY, LIGHT, NOT(BIG), NOT(HEAVY)]],
  ['🍉', [FOOD, BIG, ROUND, PLANT, HEAVY, LIQUID, BEAUTY, HUMAN, NOT(HARD)]],
  ['🍓', [FOOD, BEAUTY, PLANT, ROUND, LIGHT, NOT(BIG), NOT(HEAVY)]],
  ['🍕', [FOOD, ROUND, WARM, HUMAN, NOT(HARD), NOT(ALIVE)]],
  ['🍔', [FOOD, ROUND, WARM, BIG, HUMAN, NOT(HARD)]],
  ['🌮', [FOOD, WARM, SHARP, HUMAN, DANGER, VALUE, BEAUTY, NOT(ROUND)]],
  ['🍫', [FOOD, WARM, VALUE, BEAUTY, NOT(HARD), NOT(BIG)]],
  [
    '🍌',
    [
      FOOD,
      PLANT,
      LONG,
      LIGHT,
      WARM,
      BEAUTY,
      HUMAN,
      VALUE,
      NOT(ROUND),
      NOT(HARD),
    ],
  ],

  // Предметы быта
  ['🔑', [METAL, TOOL, HARD, SHIELD, VALUE, LIGHT, HUMAN, BEAUTY, NOT(BIG)]],
  [
    '💡',
    [LIGHT, TOOL, ROUND, WARM, VALUE, BEAUTY, HUMAN, NOT(HARD), NOT(HEAVY)],
  ],
  ['📱', [TOOL, KNOW, VALUE, HARD, LIGHT, POWER, HUMAN, NOT(HEAVY)]],
  ['⏰', [TOOL, ROUND, HARD, METAL, VALUE, HUMAN, BEAUTY, NOT(WEAPON)]],
  ['🎒', [CLOTH, SHIELD, HUMAN, HEAVY, WARM, BEAUTY, NOT(METAL), NOT(SHARP)]],
  [
    '✏️',
    [TOOL, SHARP, LONG, KNOW, BEAUTY, LIGHT, HUMAN, NOT(HEAVY), NOT(METAL)],
  ],
  [
    '📚',
    [
      KNOW,
      HARD,
      HEAVY,
      VALUE,
      BIG,
      HUMAN,
      PLANT,
      BEAUTY,
      NOT(METAL),
      NOT(ALIVE),
    ],
  ],
  ['🪣', [TOOL, LIQUID, ROUND, METAL, HEAVY, HUMAN, NOT(VALUE), NOT(SHARP)]],
  [
    '🧲',
    [
      METAL,
      POWER,
      TOOL,
      HARD,
      HEAVY,
      DANGER,
      VALUE,
      ROUND,
      HUMAN,
      NOT(BIG),
      NOT(SHARP),
    ],
  ],
  [
    '🔔',
    [METAL, ROUND, TOOL, BEAUTY, VALUE, LIGHT, HUMAN, NOT(DANGER), NOT(SHARP)],
  ],
  ['✂️', [SHARP, TOOL, METAL, DANGER, HUMAN, LIGHT, BEAUTY, NOT(BIG)]],
  ['🧸', [WARM, BEAUTY, SHIELD, HUMAN, LIGHT, ROUND, NOT(ALIVE), NOT(HARD)]],
  ['🎈', [FLIGHT, ROUND, BEAUTY, LIGHT, HUMAN, NOT(HEAVY), NOT(HARD)]],
  ['🪴', [PLANT, ALIVE, BEAUTY, ROUND, LIGHT, NOT(FAST), NOT(DANGER)]],

  // Транспорт и разное
  [
    '🚗',
    [
      FAST,
      HEAVY,
      METAL,
      BIG,
      TOOL,
      VALUE,
      HUMAN,
      ROUND,
      NOT(ALIVE),
      NOT(FLIGHT),
    ],
  ],
  [
    '✈️',
    [FLIGHT, FAST, METAL, BIG, HEAVY, TOOL, VALUE, HUMAN, ROUND, NOT(ALIVE)],
  ],
  ['🚀', [FLIGHT, FAST, POWER, METAL, TOOL, VALUE, HUMAN, BIG, NOT(ALIVE)]],
  ['⚽', [ROUND, FAST, POWER, LIGHT, HUMAN, NOT(HARD), NOT(SHARP)]],
  ['🎸', [BEAUTY, LONG, TOOL, VALUE, HUMAN, NOT(SHARP), NOT(DANGER)]],
  ['👑', [VALUE, BEAUTY, METAL, POWER, HUMAN, ROUND, NOT(WEAPON)]],
  ['💎', [VALUE, BEAUTY, HARD, LIGHT, ROUND, NOT(BIG), NOT(ALIVE)]],
  ['⭐', [LIGHT, BEAUTY, VALUE, WARM, BIG, NOT(HARD)]],
  ['🌈', [BEAUTY, LIGHT, BIG, ROUND, WARM, NOT(HARD), NOT(ALIVE)]],
  ['❤️', [ALIVE, WARM, BEAUTY, POWER, HUMAN, NOT(HARD)]],

  // Война и стихия
  [
    '🗡️',
    [
      WEAPON,
      SHARP,
      METAL,
      LONG,
      DANGER,
      HARD,
      VALUE,
      BEAUTY,
      HUMAN,
      NOT(SHIELD),
    ],
  ],
  [
    '🌊',
    [LIQUID, POWER, BIG, DANGER, BEAUTY, ALIVE, FOOD, NOT(HARD), NOT(WARM)],
  ],
  ['👗', [CLOTH, BEAUTY, HUMAN, LONG, LIGHT, WARM, NOT(HARD), NOT(HEAVY)]],
  [
    '⚓',
    [
      HEAVY,
      METAL,
      HARD,
      LIQUID,
      TOOL,
      DANGER,
      VALUE,
      HUMAN,
      ROUND,
      LONG,
      NOT(FAST),
      NOT(LIGHT),
    ],
  ],
  [
    '🛡️',
    [
      SHIELD,
      HARD,
      METAL,
      WEAPON,
      HEAVY,
      ROUND,
      VALUE,
      HUMAN,
      BEAUTY,
      NOT(SHARP),
    ],
  ],
  ['👒', [CLOTH, BEAUTY, SHIELD, WARM, LIGHT, HUMAN, ROUND, NOT(HEAVY)]],
]);
