name: Deploy to itch.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to itch.io
        uses: josephbstaton/upload-to-itch@v1.5
        with:
          # Твой секрет из настроек репозитория
          itch_username: nuclme
          itch_game_id: lighthouse
          # Канал для HTML5 игры
          itch_channel: web
          # Путь к папке с игрой
          package: ./demo-lighthouse
          # API Ключ
          api_key: ${{ secrets.BUTLER_API_KEY }}