name: Deploy to itch.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Butler
        run: |
          # Скачиваем Butler напрямую из официального хранилища через LATEST
          curl -L -o butler.zip https://dl.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Deploy to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          # Пушим папку demo-lighthouse
          ./butler push ./demo-lighthouse nuclme/lighthouse:web