name: Deploy to itch.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Используем официальный образ, где Butler уже есть внутри
    container: itchio/butler:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          # В этом образе butler вызывается просто командой 'butler'
          butler -V
          butler push ./demo-lighthouse nuclme/lighthouse:web